#version: '3'
#
#services:
#  app:
#    image: feedback:latest
#    ports:
#      - 9070:8080
#    environment:
#      SPRING_DATA_SOURCE_URL: jdbc:mysql://interview-scheduler-develop-feedbackB2B:3306/RCBTOB
#      SPRING_DATA_SOURCE_USERNAME: root
#      SPRING_DATA_SOURCE_PASSWORD: root
#    depends_on:
#      - interview-scheduler-develop-feedbackB2B
#
#  interview-scheduler-develop-feedbackB2B:
#    image: mysql:8
#    environment:
#      DATABASE_HOST: interview-scheduler-develop-feedbackB2B
#      DATABASE_PORT: 3306
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: RCBTOB
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    volumes:
#      - ./mysql:/var/lib/mysql

version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: feedback:latest
    restart: always
    build: .
    ports:
      - 9070:8080
    environment:
      MYSQL_HOST: mysqldb1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb1
    image: mysql
    volumes:
      -  ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: RCBTOB
      MYSQL_ROOT_PASSWORD: root